version: '3'
services:
    flood:
      #image: linuxserver/flood
      build: ./flood
      container_name: flood
      network_mode: 'service:vpn'
      depends_on:
          - vpn
          - rutorrent
      environment:
         PGID: 1000
         PUID: 1000
         TZ: America/Chicago
         # RTORRENT_SOCK: 'true'
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/geota/.config/flood:/config
          - /home/geota/downloads:/downloads
      restart: always
      # docker run --name rtorrent-flood  -p 3001:3000 -v /home/geota/.config/flood:/data -v /home/geota/.config/run/php/.rtorrent.sock:/data/rtorrent.sock -e RTORRENT_SOCK=true flood_rtorrent-flood
    vpn:
      sysctls:
          - net.ipv6.conf.all.disable_ipv6=0
      container_name: vpn
      #image: dperson/openvpn-client
      build:
          context: ./openvpn-client
          dockerfile: Dockerfile
      cap_add:
          - net_admin
      ports:
          - 6881:6881/udp #rutorrrent
          - 8888:80 #rutorrent
          - 5000:5000 #rutorrent
          - 3000:3000 #flood
      dns:
          - 192.168.1.1
      environment:
          TZ: 'CST6CDT'
          ROUTE: '192.168.1.0/24'
          #DNS: ''
          FIREWALL: ''
          #VPN: 'YOUR_VPN_CONNECTION_STR'
          VPNPORT: 24918
          GROUPID: 1000
      tmpfs:
         - /tmp
      restart: always
      security_opt:
         - label:disable
      devices:
         - /dev/net/tun
      volumes:
         - /dev/net:/dev/net:z
         - /home/geota/.config/vpn:/vpn      
    rutorrent:
        container_name: rutorrent
        image: linuxserver/rutorrent
        depends_on:
          - vpn
        network_mode: 'service:vpn'
        environment:
          PGID: 1000
          PUID: 1000
          TZ: America/Chicago
       #ports:
          #- 6881:6881/udp
          #- 24918:24918
          #- 8888:80
          #- 5000:5000
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/geota/.config/rutorrent:/config
          - /home/geota/downloads:/downloads
        restart: always
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        depends_on:
          - rutorrent
          - jackett
        environment:
          PGID: 1000
          PUID: 1000
          TZ: America/Chicago
        links:
         - rutorrent
         - jackett
        ports:
         - 7878:7878
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/geota/.config/radarr:/config
          - /home/geota/downloads:/downloads
          - /home/geota/downloads/movies:/movies
        restart: always
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        environment:
          PGID: 1000
          PUID: 1000
          TZ: America/Chicago
        depends_on:
          - rutorrent
          - jackett
        links:
         - rutorrent
         - jackett      
        ports:
         - 8989:8989
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/geota/.config/sonarr:/config
          - /home/geota/downloads:/downloads
          - /home/geota/downloads/tv:/tv
        restart: always
    jackett:
        container_name: jackett
        image: linuxserver/jackett
        environment:
          PGID: 1000
          PUID: 1000
          TZ: America/Chicago
        ports:
         - 9117:9117
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/geota/.config/jackett:/config
          - /home/geota/downloads/~watch:/downloads
        restart: always

