#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/flood/db,/log} \
	/downloads{/incoming,/watched}

[[ ! -e /config/flood/config.js ]] && \
	cp /app/flood/config.js /config/flood/config.js

cp  /config/flood/config.js /app/flood/config.js

# permissions
chown abc:abc \
	/downloads \
	/downloads{/incoming,/watched}

chown -R abc:abc \
	/app \
	/config
